config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  resources :users do
    resources :questions, name_prefix: "user_"
  end

  resources :questions do
    resources :answers, name_prefix: "question_"
  end

  resources :answers do
    resources :responses, :constraints => { :id => /.*/ }, name_prefix: "answer_"
  end

  get '/answers/:id/upvote', to: "answers#upvote", as: "upvote_answer"
  get '/answers/:id/downvote', to: "answers#downvote", as: "downvote_answer"
  get '/questions/:id/upvote', to: "questions#upvote", as: "upvote_question"
  get '/questions/:id/downvote', to: "questions#downvote", as: "downvote_question"

  # for BCrypt
  get '/' => 'home#index', as: :home
  get "/log_in" => "sessions#new"
  post "/log_in" => "sessions#create"
  get "/log_out" => "sessions#destroy", as: :log_out

  delete '/reponse/:id' => "responses#destroy", as: :response

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  has_many :responses
  has_many :votes, as: :voteable
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :votes, as: :voteable
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
end

app/models/user.rb
class User < ActiveRecord::Base
  #BCrypt
  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password

  has_many :questions
  has_many :answers
  has_many :responses
  has_many :votes, as: :voteable

  def self.authenticate(username, password)
    user = User.where(username: username).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voteable, polymorphic: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :get_question, only: [:create, :update]

  def create
    @answer = @question.answers.create(answer_params)
    if current_user
      @answer.update_attributes(user_id: current_user.id)
    end
    redirect_to question_path(@question)
  end

  def update
  end

  def destroy
    Answer.find(params[:id]).destroy
    redirect_to user_path(current_user)
  end

  def upvote
    @answer = Answer.find(params[:id])
    @votes = @answer.votes
    @votes.create()
    @answer.increment!(:votecount, by = 1)
    render json: @votes.size
  end

  def downvote
    @answer = Answer.find(params[:id])
    @votes = @answer.votes
    @votes.last.destroy
    @answer.decrement!(:votecount, by = 1)
    render json: @votes.size
  end


  private

  def get_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :get_question, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  def index
    if params[:order] == "new"
      @questions = Question.order(created_at: :desc)
    else
      @questions = Question.order(votecount: :desc)
    end
  end

  def new
    @question = current_user.questions.new
  end

  def create
    current_user.questions.create(question_params)
    redirect_to '/'
  end

  def show
    @answer = Answer.new
    if params[:order] == "new"
      @answers = @question.answers.order(created_at: :desc)
    else
      @answers = @question.answers.order(votecount: :desc)
    end

  end

  def edit
  end

  def update
  end

  def destroy
    Question.find(params[:id]).destroy
    redirect_to root_path
  end

  def upvote
    @votes = @question.votes
    @votes.create()
    @question.increment!(:votecount, by = 1)
    render json: @votes.size
  end

  def downvote
    @votes = @question.votes
    @votes.last.destroy
    @question.decrement!(:votecount, by = 1)
    render json: @votes.size
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def get_question
    @question = Question.find(params[:id])
  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

	def new
		@response = Response.new
		@answer = Answer.find(params[:answer_id])
		render partial: "new", locals: {response: @response}
	end

	def create
		@answer = Answer.find(params[:answer_id])
		@answer.responses << @response = Response.create(response_params)
		if current_user
			@response.update_attributes(user_id: current_user.id)
		end
		render partial: "show", locals: {response: @response}
	end

	 def destroy
    Response.find(params[:id]).destroy
    redirect_to user_path(current_user)
  end

	private
	def response_params
		params.require(:response).permit(:body)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
  @user = User.authenticate(params[:username], params[:password])
  if @user
    flash[:notice] = "You've been logged in."
    session[:user_id] = @user.id
    redirect_to questions_path
  else
    flash[:alert] = "There was a problem logging you in."
    redirect_to '/'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all.order(created_at: :desc)
	end

	def show
		@user = User.find(params[:id])
	end

	def new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "Welcome to the site!"
			session[:user_id] = @user.id
			redirect_to questions_path
		else
			flash[:alert] = "There was a problem creating your account. Please try again."
			redirect_to '/'
		end
	end

	def edit
	end

	def update
		current_user.update_attributes(user_params)
		redirect_to user_path(current_user)
	end


	private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :about)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_controller_helper.rb
module QuestionsControllerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
		@current_user = User.find(session[:user_id])
	end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="form_container">
<% if current_user %>
  <%= link_to questions_url, questions_path %>
<% else %>

	<%= link_to "Sign Up", "#", remote: true, id:"signup"%>
  <%= link_to "Log In", "#", remote: true, id:"login"%>
	  <br>
	  <br>
	  <br>
	  <br>
	  
	  <div class="forms">
  		<%= render 'forms' %>
  	</div>
  </div>
<% end %>

app/views/layouts/_login.html.erb
<section class="login_lightbox">
  <%=form_tag '../log_in' do%>
  <%=label_tag :username %>
  <%=text_field_tag :username %><br>

  <%=label_tag :password %>
  <%=password_field_tag :password %><br><br>

  <%=submit_tag "Log in" , class:"button"%>
  <% end %>
</section>

app/views/layouts/_signin.html.erb
<section class="signin_lightbox">

  <%=form_for User.new do |f| %>
    <%=f.label :username %>&nbsp;&nbsp;
    <%=f.text_field :username %><br>

    <%=f.label :password %>&nbsp;&nbsp;   
    <%=f.password_field :password %><br>

    <%=f.label :password_confirmation %>&nbsp;&nbsp;
    <%=f.password_field :password_confirmation %><br><br>

    <%=f.submit "Sign Up" , class:"button" %>
  <%end%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MacOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
</head>
<body>
  <div class="background">
  </div>
  <%= render partial: 'layouts/signin' %>
  <%= render partial: 'layouts/login' %>
  <header class="layout_header">
    <% if !current_user %>
      <a class="nav_links login_link">Login</a>
      <a class="nav_links signin_link">Sign Up</a>
    <% else %>
      <%= link_to "Sign Out", log_out_path, class: "nav_links sign_out" %>
      <%= link_to 'Profile', user_path(current_user), class: "nav_links sign_out" %>
    <% end %>
    <h1 class="title"><%= link_to image_tag("loremlogo.png"), questions_path %></h1>
  </header>
	<div class="content">
		<%= yield %>
	</div>

</body>
</html>

app/views/questions/_answer_form.html.erb
<div class="answerform">
<%= form_for [@question, @answer] do |f| %>
  <%= f.label "Add an Answer" %><br>
  <%= f.text_area :body , size:"20x8"%><br>
  <%= f.submit class:"button" %>
<% end %>
</div> 

<%= stylesheet_link_tag "app/stylesheets/index.css.scss" %>

app/views/questions/_answers.html.erb
<hr>
<% @answers.each do |answer| %>
<div class="answer_container" id=<%= answer.id %>>
  <p>Answer by <% if answer.user %>
  	<%= link_to answer.user.username, user_path(answer.user.id)%>
  	<% else %>
  	Anonymous <br>
  <% end %>
  <%= answer.created_at.strftime("%b %e, %l:%M %p") %><br><br>  <%= answer.body %></p>

  <p><a class="vote" href="/answers/<%= answer.id %>/upvote">☝︎</a>  <a class="vote" href="/answers/<%= answer.id %>/downvote">☟</a>  |  Vote Count:  <span class="vote_count"><%= answer.votes.size %></span></p>

<div class="responselink <%= answer.id %>"><%= link_to "Respond", new_answer_response_path(answer), remote: true, class: answer.id, style:"font-size: 18px;" %> </div>

	<div class="response_container" id: <%= answer.id %>>
		<% answer.responses.each do |response| %>
		<p>Response by
		<% if response.user  %>
			<%= link_to response.user.username, user_path(response.user.id)%>
			<% else %>
			Anonymous
			<% end %>
			<br>
  <%= response.created_at.strftime("%b %e, %l:%M %p") %><br><br>  <%= response.body %></p>
  <hr>
		<% end %>
	</div>

</div>
<hr>
<% end %>

<%= stylesheet_link_tag "app/stylesheets/index.css.scss" %>

app/views/questions/_form.html.erb
<%= form_for [@user, @question] do |q| %>
	<%= q.label :question %>
	Title: <%= q.text_field :title %><br>
	Body: <%= q.text_area :body %><br>
	<%= q.submit "Add a new question" %>
<% end %>

app/views/questions/_question.html.erb
<li class="question">
	<%= question.title %>
	<%= question.body %>
</li>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<div class="banner" style="padding-left: 3em; padding-bottom: 1em;"><%= image_tag("lorembanner.png") %></div>

<p style="text-align: center; font-size: 22px;">Duis Aute Irure Dolor in Reprehenderit</p>

<% if current_user %>
  <div class="new_question_button"> <%= link_to 'Ask a New Question', new_question_path, class: "button" %></div><br><br>
<% end %>
Order by:
<%= link_to "new", {controller: "questions", action: "index", :order => "new"} %> |
<%= link_to "top voted", {controller: "questions", action: "index", :order => "votesdesc"} %>

<% @questions.each do |question| %>
<article class="question_container">
  <p><%= link_to question.title, question_path(question) %><br>
  answers: <%= question.answers.count %> <span class="question_author"> by <%= link_to question.user.username, user_path(question.user.id)%> <br>
  <%= question.created_at.strftime("%b %e, %l:%M %p") %></span></p>
  <p><a class="vote" href="/questions/<%= question.id %>/upvote">☝︎</a>  <a class="vote" href="/questions/<%= question.id %>/downvote">☟</a>  |  Vote Count:  <span class="vote_count"><%= question.votes.size %></span></p>

</article>
<% end %>

<script>
var questions = document.getElementsByClassName('question_container');
	for (var i = 0; i < questions.length; i++){
		if (i % 2 == 1){
			questions[i].setAttribute("id","odd")
		}
	}
</script>

app/views/questions/new.html.erb
<h2>New Question</h2>
<div class="form_container">
  <%= form_for @question do |f| %>
    <%= f.label 'Title' %><br>
    <%= f.text_field :title %><br>

    <%= f.label 'Contents (Be Specific!)' %><br>
    <%= f.text_area :body, size: "50x15" %><br>

    <%= f.submit class:"button" %>
  <% end %>
</div>

<%= stylesheet_link_tag "app/stylesheets/index.css.scss" %>

app/views/questions/show.html.erb
<%= render 'answer_form' %>
<div class="questionheader">
  Question by <%= link_to @question.user.username, user_path(@question.user.id)%>
  <%= @question.created_at.strftime("%b %e, %l:%M %p") %>
	<br><strong><%= @question.title %></strong><br>
	 <%= @question.body %>
</div>

<div class="answersheader">
	<h3>Answers: <%= @answers.size %></h3>
	Order by:
	<%= link_to "new", {controller: "questions", action: "show", :order => "new"} %> |
	<%= link_to "top voted", {controller: "questions", action: "show", :order => "votesdesc"} %>
</div>
<%= render 'answers' %>

<%= stylesheet_link_tag "app/stylesheets/index.css.scss" %>

app/views/responses/_form.html.erb
<%= form_for [@answer, @response] do |f| %>
  <%= f.label "Response Body" %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/responses/_new.html.erb
<%= form_for [@answer, @response], remote: true, :html => {:class => @answer.id} do |f| %>
  &nbsp;<%= f.label "New Response" %><br>
  <%= f.text_area :body, size: "60x5" %><br>
  <%= f.submit class:"button" %>
<% end %>


<%= stylesheet_link_tag "app/stylesheets/index.css.scss" %>

app/views/responses/_show.html.erb
<p>Response by 
		<% if current_user  %>
			<%= link_to current_user.username, user_path(current_user.id)%> 
			<% else %>
			Anonymous
			<% end %>
			<br>
  <%= response.created_at.strftime("%b %e, %l:%M %p") %><br><br>  <%= response.body %></p>
 
		

app/views/responses/index.html.erb
<h2>Answer ID: <%= @answer.id %></h2>

<% @responses.each do |r| %>
  <%= r.body %>
<% end %>

app/views/responses/new.html.erb
<%= render 'form' %>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>
<div class="form_container">
<%= form_for current_user do |f| %>
  <%= f.label 'Username' %><br>
  <%= f.text_field :username %><br>

  <%= f.label 'About Me' %><br>
  <%= f.text_area :about, size: "50x15"%><br>
  <%= f.submit class:"button"%>
<% end %>
</div>

<%= stylesheet_link_tag "app/stylesheets/index.css.scss" %>

app/views/users/index.html.erb
<div id="welcome">
  <div class="form_container">
      <h1>Mac_Overflow</h1>

      <%= link_to "Sign Up", "#", remote: true, id:"signup"%>
      <%= link_to "Log In", "#", remote: true, id:"login"%>
  
    </div><br>

  <div class="signup" style="display: none;">
  <h2>SIGN UP</h2>
    <%=form_for :user, url: users_path do |f| %>
      Username: <%= f.text_field :username %>
      Password: <%= f.password_field :password  %>
      <%= f.submit %>
    <%end %>
  </div>


<div class="login" style="display: none;">
   <h2>LOG IN</h2>
   <%=form_for :session do |f| %>
      Username: <%= f.text_field :username %>
      Password: <%= f.password_field :password  %>
      <%= f.submit %>
    <%end %>
  </div>

app/views/users/show.html.erb
<section class="user_about_section">
	<p class="about_title">About:</p>
	<article class="text_area">
		<% if @user.about == nil %>
			Help people know more about you
		<% else %>
			<%= @user.about %>
		<% end %>
	</article>
</section>

<div class="username_container">
	<h1 class="username"><%= @user.username %>
	<% if current_user != nil && @user == current_user  %>
		<span class="edit_user_button"><%= link_to 'Edit', edit_user_path(@user) %></span>
	<% end %>
	</h1>
</div>

<div id="accordion">

	<h3 class="accordion_title">QUESTIONS SUBMITTED: <%= @user.questions.size %></h3>
		<div class="question accordion_divs">
			<% count = 1 %>
			<% @user.questions.each do |q| %>
					<a href="<%= question_url(q) %>"><%= count %>. <strong><%= q.title %></strong></a><br>
					<%= q.body %><br>
					<% if current_user != nil && @user == current_user  %>
						<%= link_to 'Delete', question_path(q), method: :delete %><br>
					<% end %>
					<% count += 1 %>
			<% end %>
		</div>

	<h3 class="accordion_title">ANSWERS SUBMITTED: <%= @user.answers.size %></h3>
	  <div class="answer accordion_divs">
			<% count = 1 %>
			<% @user.answers.each do |a| %>
				<%="#{count}. #{a.body} "%><br>
				<% if current_user != nil && @user == current_user  %>
					<%= link_to 'Delete', answer_path(a), method: :delete %><br>
				<% end %>
				<% count += 1 %>
			<% end %>
		</div>


	<h3 class="accordion_title">COMMENTS SUBMITTED: <%= @user.responses.size %></h3>
		<div class="comment accordion_divs">
			<% count = 1 %>
			<% @user.responses.each do |r| %>
				<%="#{count}. #{r.body} "%><br>
				<% if current_user != nil && @user == current_user  %>
					<%= link_to 'Delete', response_path(r), method: :delete %><br>
				<% end %>
				<% count += 1 %>
			<% end %>
		</div>

<% if current_user != nil && @user == current_user  %>
		<span class="edit_user_button"><%= link_to 'Edit Profile', edit_user_path(@user) %></span>
	<% end %>
</div>